markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Zhenlong's Blog"
markdown: rdiscount

author: "Zhenlong"
atom-baseurl: "http://zhenlonghe.github.io/"
disqus: "zhenlonghe"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.flickr.com/photos/127518998@N02/
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

